"""Canonical column names for the FinViz Elite USA full export (v=152).

Every fetch of ``FINVIZ_USA_FULL_V152_EXPORT`` returns one row per symbol with these
headers (exact strings). Import ``USA_V152`` and use ``USA_V152.TICKER``,
``USA_V152.VOLATILITY_W``, etc., with ``_get_csv_val(row, USA_V152.TICKER, ...)``
so code does not drift from the live sheet.

**Duplicate header:** FinViz lists ``Dividend`` twice; CSV parsers typically keep one
cell per name. Treat dividend-related fields carefully or inspect raw row keys.

**Last column:** FinViz may label the final column ``Tag`` or ``Tags``; both are listed.
"""

from __future__ import annotations

from typing import Final


class USA_V152:
    """Elite screener export column labels (v=152 full USA)."""

    NO: Final = "No."
    TICKER: Final = "Ticker"
    COMPANY: Final = "Company"
    INDEX: Final = "Index"
    SECTOR: Final = "Sector"
    INDUSTRY: Final = "Industry"
    COUNTRY: Final = "Country"
    EXCHANGE: Final = "Exchange"
    MARKET_CAP: Final = "Market Cap"
    PE: Final = "P/E"
    FWD_PE: Final = "Fwd P/E"
    PEG: Final = "PEG"
    PS: Final = "P/S"
    PB: Final = "P/B"
    PC: Final = "P/C"
    P_FCF: Final = "P/FCF"
    BOOK_SH: Final = "Book/sh"
    CASH_SH: Final = "Cash/sh"
    DIVIDEND: Final = "Dividend"  # appears twice in FinViz layout
    DIVIDEND_TTM: Final = "Dividend TTM"
    DIVIDEND_EX_DATE: Final = "Dividend Ex Date"
    DIVIDEND_GR_1Y: Final = "Dividend Gr. 1Y"
    DIVIDEND_GR_3Y: Final = "Dividend Gr. 3Y"
    DIVIDEND_GR_5Y: Final = "Dividend Gr. 5Y"
    PAYOUT_RATIO: Final = "Payout Ratio"
    EPS: Final = "EPS"
    EPS_NEXT_Q: Final = "EPS next Q"
    EPS_THIS_Y: Final = "EPS This Y"
    EPS_NEXT_Y: Final = "EPS Next Y"
    EPS_PAST_3Y: Final = "EPS Past 3Y"
    EPS_PAST_5Y: Final = "EPS Past 5Y"
    EPS_NEXT_5Y: Final = "EPS Next 5Y"
    SALES_PAST_3Y: Final = "Sales Past 3Y"
    SALES_PAST_5Y: Final = "Sales Past 5Y"
    SALES_Q_Q: Final = "Sales Q/Q"
    EPS_Q_Q: Final = "EPS Q/Q"
    EPS_YOY_TTM: Final = "EPS YoY TTM"
    SALES_YOY_TTM: Final = "Sales YoY TTM"
    SALES: Final = "Sales"
    INCOME: Final = "Income"
    EPS_SURPRISE: Final = "EPS Surprise"
    REVENUE_SURPRISE: Final = "Revenue Surprise"
    ENTERPRISE_VALUE: Final = "Enterprise Value"
    EV_EBITDA: Final = "EV/EBITDA"
    EV_SALES: Final = "EV/Sales"
    OUTSTANDING: Final = "Outstanding"
    FLOAT: Final = "Float"
    FLOAT_PCT: Final = "Float %"
    INSIDER_OWN: Final = "Insider Own"
    INSIDER_TRANS: Final = "Insider Trans"
    INST_OWN: Final = "Inst Own"
    INST_TRANS: Final = "Inst Trans"
    SHORT_FLOAT: Final = "Short Float"
    SHORT_RATIO: Final = "Short Ratio"
    SHORT_INTEREST: Final = "Short Interest"
    ROA: Final = "ROA"
    ROE: Final = "ROE"
    ROIC: Final = "ROIC"
    CURR_R: Final = "Curr R"
    QUICK_R: Final = "Quick R"
    LTDEBT_EQ: Final = "LTDebt/Eq"
    DEBT_EQ: Final = "Debt/Eq"
    GROSS_M: Final = "Gross M"
    OPER_M: Final = "Oper M"
    PROFIT_M: Final = "Profit M"
    PERF_1_MIN: Final = "Perf 1 Min"
    PERF_2_MIN: Final = "Perf 2 Min"
    PERF_3_MIN: Final = "Perf 3 Min"
    PERF_5_MIN: Final = "Perf 5 Min"
    PERF_10_MIN: Final = "Perf 10 Min"
    PERF_15_MIN: Final = "Perf 15 Min"
    PERF_30_MIN: Final = "Perf 30 Min"
    PERF_1_HR: Final = "Perf 1 Hr"
    PERF_2_HR: Final = "Perf 2 Hr"
    PERF_4_HR: Final = "Perf 4 Hr"
    PERF_WEEK: Final = "Perf Week"
    PERF_MONTH: Final = "Perf Month"
    PERF_QUART: Final = "Perf Quart"
    PERF_HALF: Final = "Perf Half"
    PERF_YTD: Final = "Perf YTD"
    PERF_YEAR: Final = "Perf Year"
    PERF_3Y: Final = "Perf 3Y"
    PERF_5Y: Final = "Perf 5Y"
    PERF_10Y: Final = "Perf 10Y"
    BETA: Final = "Beta"
    ATR: Final = "ATR"
    VOLATILITY_W: Final = "Volatility W"
    VOLATILITY_M: Final = "Volatility M"
    SMA20: Final = "SMA20"
    SMA50: Final = "SMA50"
    SMA200: Final = "SMA200"
    HIGH_50D: Final = "50D High"
    LOW_50D: Final = "50D Low"
    HIGH_52W: Final = "52W High"
    LOW_52W: Final = "52W Low"
    RANGE_52W: Final = "52W Range"
    ALL_TIME_HIGH: Final = "All-Time High"
    ALL_TIME_LOW: Final = "All-Time Low"
    RSI: Final = "RSI"
    EARNINGS: Final = "Earnings"
    IPO_DATE: Final = "IPO Date"
    OPTIONABLE: Final = "Optionable"
    SHORTABLE: Final = "Shortable"
    EMPLOYEES: Final = "Employees"
    CHANGE_FROM_OPEN: Final = "Change from Open"
    GAP: Final = "Gap"
    RECOM: Final = "Recom"
    AVG_VOLUME: Final = "Avg Volume"
    REL_VOLUME: Final = "Rel Volume"
    VOLUME: Final = "Volume"
    TRADES: Final = "Trades"
    TARGET_PRICE: Final = "Target Price"
    PREV_CLOSE: Final = "Prev Close"
    OPEN: Final = "Open"
    HIGH: Final = "High"
    LOW: Final = "Low"
    PRICE: Final = "Price"
    CHANGE: Final = "Change"
    AH_CLOSE: Final = "AH Close"
    AH_CHANGE: Final = "AH Change"
    AH_VOLUME: Final = "AH Volume"
    NEWS_TIME: Final = "News Time"
    NEWS_URL: Final = "News URL"
    NEWS_TITLE: Final = "News Title"
    DAILY_DIGEST: Final = "Daily Digest"
    SINGLE_CATEGORY: Final = "Single Category"
    ASSET_TYPE: Final = "Asset Type"
    ETF_TYPE: Final = "ETF Type"
    SECTOR_THEME: Final = "Sector/Theme"
    REGION: Final = "Region"
    ACTIVE: Final = "Active"
    EXPENSE: Final = "Expense"
    HOLDINGS: Final = "Holdings"
    AUM: Final = "AUM"
    NAV: Final = "NAV"
    NAV_PCT: Final = "NAV%"
    FLOWS_1M: Final = "Flows 1M"
    FLOWS_PCT_1M: Final = "Flows% 1M"
    FLOWS_3M: Final = "Flows 3M"
    FLOWS_PCT_3M: Final = "Flows% 3M"
    FLOWS_YTD: Final = "Flows YTD"
    FLOWS_PCT_YTD: Final = "Flows% YTD"
    FLOWS_1Y: Final = "Flows 1Y"
    FLOWS_PCT_1Y: Final = "Flows% 1Y"
    RETURN_PCT_1Y: Final = "Return% 1Y"
    RETURN_PCT_3Y: Final = "Return% 3Y"
    RETURN_PCT_5Y: Final = "Return% 5Y"
    RETURN_PCT_10Y: Final = "Return% 10Y"
    RETURN_PCT_SI: Final = "Return% SI"
    TAG: Final = "Tag"
    TAGS: Final = "Tags"


# Legacy / alternate spellings sometimes seen in older exports or merged views.
# Use with ``_get_csv_val(row, *ALIASES["price"])`` etc. from ``data_fetcher``.
ALIASES: dict[str, tuple[str, ...]] = {
    "ticker": (USA_V152.TICKER, "ticker"),
    "index": (USA_V152.INDEX, "index"),
    "market_cap": (USA_V152.MARKET_CAP, "market_cap"),
    "price": (USA_V152.PRICE, "price", "Last", "Close", "Last Price"),
    "change": (USA_V152.CHANGE, "change", "Change %", "Change%"),
    "volume": (USA_V152.VOLUME, "volume"),
    "avg_volume": (USA_V152.AVG_VOLUME, "Average Volume", "avg_volume"),
    "rel_volume": (USA_V152.REL_VOLUME, "Relative Volume", "rel_volume"),
    "volatility_w": (USA_V152.VOLATILITY_W, "Volatility Week"),
    "volatility_m": (USA_V152.VOLATILITY_M, "Volatility Month"),
}


class V152_PARSED:
    """Column names on the normalized DataFrame from ``_parse_group_indicators_rows`` / ``get_parsed_usa_v152_df``.

    These are snake_case pipeline fields (not raw FinViz headers). Use for ``df[col]`` and intraday row dicts.
    """

    TICKER: Final = "ticker"
    CLOSE: Final = "close"
    PREV_CLOSE: Final = "prev_close"
    OPEN_PRICE: Final = "open_price"
    OPEN: Final = "open"  # often same as open_price in merged exports
    DAY_CHG: Final = "day_chg"
    OPEN_CHG: Final = "open_chg"
    WEEK_CHG: Final = "week_chg"
    MONTH_CHG: Final = "month_chg"
    QTR_CHG: Final = "qtr_chg"
    HALF_CHG: Final = "half_chg"
    YEAR_CHG: Final = "year_chg"
    SMA10: Final = "sma10"
    SMA20: Final = "sma20"
    SMA50: Final = "sma50"
    SMA200: Final = "sma200"
    EMA10: Final = "ema10"
    ATR: Final = "atr"
    ATR_PCT: Final = "atr_pct"
    VOLATILITY_WEEK: Final = "volatility_week"
    VOLATILITY_MONTH: Final = "volatility_month"
    HIGH_20: Final = "high_20"
    LOW_20: Final = "low_20"
    PRICE_TO_20_RANGE: Final = "price_to_20_range"
    HIGH_52W: Final = "high_52w"
    LOW_52W: Final = "low_52w"
    VOLUME: Final = "volume"
    AVG_VOLUME: Final = "avg_volume"
    REL_VOLUME: Final = "rel_volume"
    MARKET_CAP: Final = "market_cap"
    NEW_20_HIGH: Final = "new_20_high"
    NEW_20_LOW: Final = "new_20_low"
    INDUSTRY: Final = "industry"
    SECTOR: Final = "sector"
    NEWS_TIME: Final = "news_time"
    NEWS_TITLE: Final = "news_title"
    NEWS_URL: Final = "news_url"
    DAILY_DIGEST: Final = "daily_digest"
